### ISSUE TITLE
Release or tag for ROCm 2.9?

### ISSUE THREAD

**Issue by justxi** [ROCmSoftwarePlatform/rocSOLVER#19]
Hi,

will there be a release or tag for ROCm 2.9?
This would make packaging easier.

**Comment by justxi** [comment]
... or 2.10?

**Comment by saadrahim** [comment]
Hi @justxi,

This was missed by us. We will have a tag made for 2.10 shortly.

**Comment by justxi** [comment]
Ok, thanks.

**Comment by justxi** [comment]
https://github.com/ROCmSoftwarePlatform/rocSOLVER/releases
