### ISSUE TITLE
[feature request] rocsolver_zgetrs and rocsolver_getri_batched

### ISSUE THREAD

**Issue by ye-luo** [ROCmSoftwarePlatform/rocSOLVER#20]
rocsolver_zgetrs is the complex version of rocsolver_dgetrs
rocsolver_getri_batched is used after rocsolver_getrf_batched to complete matrix inversion in a batched fashion.

Question: Does the mention of rocsolver_getrf in README.md refer to availability of all the s/c/d/z versions?

**Comment by jzuniga-amd** [comment]
Only single and double precisions (s/d) are currently supported by rocsolver. Complex precisions (c/z) will be added in future releases. The addition of functions getri, getri_batched, as well as getrs_batched is already planned (for s/d precisions).

**Comment by jzuniga-amd** [comment]
Complex versions (c/z) of GETRS as well as GETF2/GETRF have been added
