### ISSUE TITLE
Symmetric eigensolvers missing

### ISSUE THREAD

**Issue by elbriggs** [ROCmSoftwarePlatform/rocSOLVER#235]
I'm not sure if this is a Ubuntu packaging problem or some issue with synchronization of docs and code but the ROCm documentation here https://rocmdocs.amd.com/en/latest/ lists symmetric eigensolver routines in rocsolver. I installed the 4.1 Ubuntu packages but the functions are not there.

**Comment by cgmb** [comment]
It appears that the main ROCm docs page is linking to the latest version of the rocsolver documentation, which is for the (unreleased) rocSOLVER 3.13.0. ROCm 4.1.0 ships with rocSOLVER 3.11.0, which is documented here: https://rocsolver.readthedocs.io/en/rocm-4.1.0/.

The develop branch [CHANGELOG](https://github.com/ROCmSoftwarePlatform/rocSOLVER/blob/develop/CHANGELOG.md) can give some indication of what features are planned to appear in upcoming ROCm releases, though it's not set in stone until the actual release is made.

**Comment by cgmb** [comment]
I've updated the rocSOLVER documentation. The link from https://rocmdocs.amd.com/en/latest/ should now take you to the rocSOLVER documentation for ROCm 4.1.0.

**Comment by elbriggs** [comment]
Thanks Cory. I'll go ahead and close this.
