### ISSUE TITLE
Segfault with batched syev/heev from ROCm 4.2.0

### ISSUE THREAD

**Issue by leofang** [ROCmSoftwarePlatform/rocSOLVER#295]
Hello, I am a CuPy core contributor working on supporting the new eigensolvers in CuPy, but I found that the batched version would just segfault (the non-batched version works fine and passes our tests). Below is a super minimal reproducer:
```C++
#include <iostream>
#include <algorithm> // for std::min
#include <stddef.h>  // for size_t
#include <vector>
#include <hip/hip_runtime_api.h> // for hip functions
#include <rocsolver.h> // for all the rocsolver C interfaces and type declarations

int main() {
  int batch_size = 2;
  rocblas_int M = 3;
  rocblas_int N = 3;
  rocblas_int lda = 3;

  rocblas_handle handle;
  rocblas_create_handle(&handle);

  size_t size_A = size_t(lda) * N;

  // A = [ [1, 2, 3,
  //        2, 5, 4,
  //        3, 4, 9],
  //       [2, 2, 3,
  //        2, 6, 4,
  //        3, 4, 10]]
  std::vector<float> hA = {1, 2, 3, 2, 5, 4, 3, 4, 9, 2, 2, 3, 2, 6, 4, 3, 4, 10}; // creates array for matrix in CPU

  float *dA, *dW, *dE;
  hipMalloc(&dA, sizeof(float)*size_A*batch_size);
  hipMalloc(&dW, sizeof(float)*M*batch_size);
  hipMalloc(&dE, sizeof(float)*M*batch_size);
  int *info;
  hipMalloc(&info, sizeof(int)*batch_size);

  hipMemcpy(dA, hA.data(), sizeof(float)*size_A*batch_size, hipMemcpyHostToDevice);
  rocblas_status status;

  #ifdef DO_BATCH
  // this would segfault
  status = rocsolver_ssyev_batched(handle, rocblas_evect_original, rocblas_fill_upper,
                                   N, reinterpret_cast<float* const*>(dA), lda,
                                   dW, N,
                                   dE, N, info, batch_size);
  if (status != 0) {
    std::cout << "got error: " << status << std::endl;
    exit(1);
  }
  #else
  // but this would not
  status = rocsolver_ssyev(handle, rocblas_evect_original, rocblas_fill_upper,
                           N, dA, lda,
                           dW,
                           dE, info);
  if (status != 0) {
    std::cout << "got error: " << status << std::endl;
    exit(1);
  }
  #endif

  // don't bother doing cleanup as it's unimportant here...
  return 0;
}
```
When compiled with
```
hipcc test_batched_syev.cpp -I$ROCM_PATH/include -L$ROCM_PATH/lib -lrocblas -lrocsolver -o test_batched_syev
```
the non-batched version is called (and operates on the first matrix in A) and runs fine, but when compiled with
```
hipcc test_batched_syev.cpp -I$ROCM_PATH/include -L$ROCM_PATH/lib -lrocblas -lrocsolver -DDO_BATCH -o test_batched_syev
```
the batched version is called and segfaults:
```
$ ./test_batched_syev
:0:rocdevice.cpp            :2533: 47346961354 us: Device::callbackQueue aborting with error : HSA_STATUS_ERROR_MEMORY_APERTURE_VIOLATION:  The agent attempted to access memory beyond the largest legal address. code: 0x29
Aborted (core dumped)
```
This happens for all four types (ssyev, dsyev, cheev, zheev), so I assume the bug might be in the type dispatch layer?

cc: @amathews-amd (for awareness)

**Comment by cgmb** [comment]
In `rocsolver_ssyev_batched`, the parameter `dA` should be an array of pointers (e.g. `std::array<float*,2>`). The function you'd want for the data layout in your example is `rocsolver_ssyev_strided_batched`.

**Comment by leofang** [comment]
@cgmb Thanks for speedy reply! Although it is confusing: If you look at batched gesvd, it also takes an array of pointers (`T* const A[]`), see
https://github.com/ROCmSoftwarePlatform/rocSOLVER/blob/22e94fd40ef390cfce410dc9bb8cefc8f7239c45/library/include/rocsolver-functions.h#L10006-L10025
But when we cast `A` to `T* const*` and pass to gesvd routines (following the way we launch cuSOLVER's routines), it works just fine since its advent in ROCm 3.9.0 without any issue:
https://github.com/cupy/cupy/blob/4469fae998df33c72ff40ef954cb08b8f0004b18/cupy_backends/hip/cupy_rocsolver.h#L1084-L1093
Shouldn't syev/heev behave similarly? What's the catch here?

If such casting is not allowed I'd expect at least a compiler error...

**Comment by leofang** [comment]
I still get a segfault when I replace `reinterpret_cast<float* const*>(dA)` by `a.data()`, where `a` is constructed as a vector:
```C++
    std::vector<float*> a(batchSize);
    for (int i=0; i<batchSize; i++) {
        a[i] = A + i * (lda * n);
    }
```
I don't think using `std::array` makes sense here because the input size is determined at runtime (Python sessions).

**Comment by leofang** [comment]
Oh I missed this naive try would not work unless `a` is moved to GPU. Hold on...

**Comment by leofang** [comment]
Thank you for prompt hep with my silliness, @cgmb! 😅 I forgot that when adding the support of gesvd I had a helper to construct `T* const A[]` for me...
https://github.com/cupy/cupy/blob/d3c46cfdba25c4d0892b76a4f89e757a3bd05e18/cupy/cusolver.pyx#L221-L225
I am closing this issue as resolved.

**Comment by leofang** [comment]
Just a little follow-up: I was able to expose the new `syev`/`heev` solvers to CuPy and all tests pass now. Thanks again @cgmb for bearing with my silliness! 😄
