### ISSUE TITLE
Low performance for medium size matrices

### ISSUE THREAD

**Issue by gh6576** [ROCmSoftwarePlatform/rocSOLVER#312]
I use the example code to do QR factorization for matrices of different sizes and I get the following results:

QR factorization of a rank 3 matrix took 34701 microseconds
QR factorization of a rank 30 matrix took 1316 microseconds
QR factorization of a rank 300 matrix took 5766996 microseconds
QR factorization of a rank 3000 matrix took 71824 microseconds
QR factorization of a rank 30000 matrix took 473530 microseconds

It looks like calculating a medium-size matrix is really slow. Is it a bug or intended?

**Comment by jzuniga-amd** [comment]
Hi, could you please provide more information on how you are calling the functions? Maybe a sample code? How are you timing the calls? What do you mean by rank 3, 30, 300... ? Are these the sizes of square matrices?

Assuming you are calling `rocsolver_dgeqrf` in double precision for sizes m=n=3,30,300,..., I got the following execution times using the **rocsolver-bench** client: 

m=n=3, 171 microseconds
m=n=30, 1287 microseconds
m=n=300, 14655 microseconds
m=n=3000, 201572 microseconds
m=n=30000, 19750572 microseconds

(QR is not a rank-revealing method so the rank of the matrix does not really matter for the execution time, but we use a random input matrix for the test that we scale to be full-rank anyways.)

So, I don't observe any weird behaviour.

**Comment by gh6576** [comment]
Thanks for your reply. 
I append the code at the end. Nothing much is changed from the example code. I just adjust the matrix and use the chrono package for timing  (I don't have the rocsolver-bench client on the cluster and probably I am not allowed to install it.)
By 'rank', I mean m and n for the square matrices. Sorry for causing confusion. 
And I have more results here (by a for loop):

QR factorization of m=n=2 matrix took 347516 microseconds
QR factorization of m=n=4 matrix took 1367 microseconds
QR factorization of m=n=8 matrix took 463 microseconds
QR factorization of m=n=16 matrix took 791 microseconds
QR factorization of m=n=32 matrix took 1479 microseconds
QR factorization of m=n=64 matrix took 3761 microseconds
QR factorization of m=n=128 matrix took 6394 microseconds
QR factorization of m=n=256 matrix took 5772862 microseconds
QR factorization of m=n=512 matrix took 38466 microseconds
QR factorization of m=n=1024 matrix took 84774 microseconds
QR factorization of m=n=2048 matrix took 166706 microseconds
QR factorization of m=n=4096 matrix took 342538 microseconds

For m=n=2, there is a reasonable function overhead. The only abnormal thing is for m=n=256.

Then I remove the for loop and calculate a single matrix. I find as long as m=n<=128, the time is always about 30000 microseconds. However, calculating any matrix larger than 128 took about 6 seconds. It seems we encounter another large function overhead. Then I do the for loop in the reverse order and get:

QR factorization of m=n=4096 matrix took 6474653 microseconds
QR factorization of m=n=2048 matrix took 127005 microseconds
QR factorization of m=n=1024 matrix took 81086 microseconds
QR factorization of m=n=512 matrix took 41147 microseconds
QR factorization of m=n=256 matrix took 18411 microseconds
QR factorization of m=n=128 matrix took 7362 microseconds
QR factorization of m=n=64 matrix took 3595 microseconds
QR factorization of m=n=32 matrix took 1761 microseconds
QR factorization of m=n=16 matrix took 887 microseconds
QR factorization of m=n=8 matrix took 482 microseconds
QR factorization of m=n=4 matrix took 264 microseconds
QR factorization of m=n=2 matrix took 163 microseconds

Why there is such a large overhead for matrices larger than 128?




The code:
`#include <algorithm> // for std::min
#include <stdio.h>   // for size_t, printf
#include <vector>
#include <hip/hip_runtime_api.h> // for hip functions
#include <rocsolver.h> // for all the rocsolver C interfaces and type declarations
#include <iostream>
#include <chrono>
// Example: Compute the QR Factorization of a matrix on the GPU

void get_example_matrix(std::vector<double>& hA,
                        rocblas_int& M,
                        rocblas_int& N,
                        rocblas_int& lda) {
  N = M;
  lda = M;
  hA.resize(size_t(lda) * N);
  for (size_t i = 0; i < M; ++i) {
    for (size_t j = 0; j < N; ++j) {
      // copy A (2D array) into hA (1D array, column-major)
      hA[i + j*lda] = std::rand() % 1;
    }
  }
}

int main() {
  rocblas_int M = 2;
  rocblas_int N;          // cols
  rocblas_int lda;        // leading dimension
  std::vector<double> hA; // input matrix on CPU
  // initialization
  rocblas_handle handle;
  rocblas_create_handle(&handle);
  get_example_matrix(hA, M, N, lda);

  // calculate the sizes of our arrays
  size_t size_A = size_t(lda) * N;          // count of elements in matrix A
  size_t size_piv = size_t(std::min(M, N)); // count of Householder scalars

  // allocate memory on GPU
  double *dA, *dIpiv;
  hipMalloc(&dA, sizeof(double)*size_A);
  hipMalloc(&dIpiv, sizeof(double)*size_piv);

  //timing
  using micro = std::chrono::microseconds;
  auto start = std::chrono::high_resolution_clock::now();
  // copy data to GPU
  hipMemcpy(dA, hA.data(), sizeof(double)*size_A, hipMemcpyHostToDevice);

  // compute the QR factorization on the GPU
  rocsolver_dgeqrf(handle, M, N, dA, lda, dIpiv);

  // copy the results back to CPU
  std::vector<double> hIpiv(size_piv); // array for householder scalars on CPU
  hipMemcpy(hA.data(), dA, sizeof(double)*size_A, hipMemcpyDeviceToHost);
  hipMemcpy(hIpiv.data(), dIpiv, sizeof(double)*size_piv, hipMemcpyDeviceToHost);

  auto finish = std::chrono::high_resolution_clock::now();
  std::cout << "QR factorization of m=n=" << M <<" matrix took "
      << std::chrono::duration_cast<micro>(finish - start).count()
      << " microseconds\n";
  // clean up
  hipFree(dA);
  hipFree(dIpiv);
  rocblas_destroy_handle(handle);
}
`

**Comment by cgmb** [comment]
The rocSOLVER examples were updated to mention `rocblas_initialize()` in ROCm 5.0. There are also some optimizations to `rocblas_initialize()` coming in future versions of rocBLAS.
