### ISSUE TITLE
Low performance of batched zgetrs on MI100

### ISSUE THREAD

**Issue by bd4** [ROCmSoftwarePlatform/rocSOLVER#326]
I have a batched zgetrs case, with 140x140 matrices, 1 rhs, and 384 batches. This case averages around 0.090 seconds on MI100 (ROCm 4.2 and 4.3), and on summit with a V100, it averages 0.00055, around 163 times faster. This is currently the biggest bottleneck running our test case on 3 spock nodes.

Here is a reproducer:
https://github.com/bd4/hip-bugs/blob/main/batched_zgetrs.cxx
it needs this file decompressed to same directory to read input data from:
https://www.mcs.anl.gov/~ballen/zgetrs.txt.bz2
around 260MB uncompressed.

I see there has been performance work recently on getrf - should this affect getrs as well?

**Comment by bd4** [comment]
I should add that this is double precision, I have not tested single precision yet. Also note that this performance difference scales down to consumer GPUs, e.g. nVidia 1070 Ti averages .003, gfx803 RX 570 averages 0.27. Not as close a comparison here, but I think the RX 570 should have roughly similar double precision performance to the the 1070, since the 1070 has more crippled double precision performance vs single.

**Comment by bd4** [comment]
I updated the reproducer on github, to just use identity matrices and pivot [1,2,3...], so it doesn't have to read the matrices from file.

**Comment by tfalders** [comment]
Recent commits to rocBLAS and rocSOLVER should vastly improve the runtime of getrs for the given problem size. In my tests on MI100, I've been seeing a 2x slowdown in comparison to the reported V100 time, as opposed to the original 163x.
rocBAS: 895b9645d7f0905a66bd5dff21d22a4e7f0fe383
rocSOLVER: bdccf2b519f0319ae8a1487a68366fb57da232a0

We'll continue investigating to see if we can reach parity with the reported V100 time.

**Comment by bd4** [comment]
I can test this with the gtensor benchmarks. Is the fix commit part of 5.2 release, or should I build from source and make sure is using custom version?

**Comment by tfalders** [comment]
The fix commit will be part of the next release. For now it will need to be built from source.

**Comment by bd4** [comment]
I built rocBLAS and rocSOLVER from source on my test machine with a W6800 (gfx1030), and I see around 2x speedup when I set LD_LIBRARY_PATH to use newly build version vs vanilla ROCm 5.2.0. I am struggling to get them built on machines with MI100 and MI250X, but W6800 results are promising.

Particularly for rocBLAS, a more non-root friendly dependency build option would be helpful in install.sh.
