### ISSUE TITLE
rocblas_evect type definition not found in rocblas_module.f90

### ISSUE THREAD

**Issue by Madu86** [ROCmSoftwarePlatform/rocSOLVER#349]
Hello, I am working on a fortran driver to use rocsolver_dsyevd. Since there is no wrapper function available (at least to my knowledge), I looked at your basic fortran example and wrote the following in my driver. 

```
    interface
        function rocsolver_dsyevd(handle, evect, uplo, N, A, lda, D, E, info) &
                result(c_int) &
                bind(c, name = 'rocsolver_dsyevd')
            use iso_c_binding
            implicit none
            type(c_ptr), value :: handle
            integer(kind(rocblas_evect_original)), value :: evect
            integer(kind(rocblas_fill_full)), value :: uplo
            integer(c_int), value :: N
            type(c_ptr), value :: A
            integer(c_int), value :: lda
            type(c_ptr), value :: D
            type(c_ptr), value :: E
            type(c_ptr), value :: info
        end function rocsolver_dsyevd
    end interface
```
According to rocSolver manual, I am supposed to pass a `rocblas_evect` type parameter into the function; but this type doesnt exist in rocblas_module.f90 of rocm 4.5. I am thinking about having something like below in my driver as a quick fix. But I dont know what are the correct integers to assign. Can you please help me with this? 

```
    enum, bind(c)
      enumerator :: rocblas_evect_original = foo_int
        enumerator :: rocblas_evect_tridiagonal = bar_int
        enumerator :: rocblas_evect_none = baz_int
    end enum
```

Thanks!

**Comment by cgmb** [comment]
The values for all of rocSOLVER's extra enums can be found in [rocsolver-extra-types.h](https://github.com/ROCmSoftwarePlatform/rocSOLVER/blob/rocm-4.5.0/library/include/rocsolver-extra-types.h). For that particular enum, the values are:
```
rocblas_evect_original = 211
rocblas_evect_tridiagonal = 212
rocblas_evect_none = 213
```

**Comment by Madu86** [comment]
Great! Thanks!
