### ISSUE TITLE
`HSA_STATUS_ERROR_ILLEGAL_INSTRUCTION` in `rocsolver_dgels_batched`

### ISSUE THREAD

**Issue by XzzX** [ROCmSoftwarePlatform/rocSOLVER#443]
I am playing around with the batched dgels implementation. However, I cannot run more than one call. The second call crashes with `:0:rocdevice.cpp            :2614: 1042550426289 us: 1410912: [tid:0x155505b6a700] Device::callbackQueue aborting with error : HSA_STATUS_ERROR_ILLEGAL_INSTRUCTION: The agent attempted to execute an illegal shader instruction. code: 0x2a`

Any ideas? Thanks.

```
hipcc --version
HIP version: 5.1.20531-cacfa990
AMD clang version 14.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-5.1.0 22114 5cba46feb6af367b1cafaa183ec42dbfb8207b14)
```

[Source Code](https://github.com/ROCmSoftwarePlatform/rocSOLVER/files/8939210/example.txt)

**Comment by cgmb** [comment]
There are some errors relating to `d_info` in your example. This allocation is not sufficient:
```cpp
rocblas_int *d_info;
CHECK(hipMalloc(&d_info, sizeof(rocblas_int)));
```
In [the docs for `rocsolver_dgels_batched`](https://rocsolver.readthedocs.io/en/rocm-5.1.3/api_lapackfunc.html#c.rocsolver_dgels_batched), the info parameter is described as an "array of batch_count integers on the GPU." The batch size is 131072, so rocsolver will be writing roughly half a megabyte of info values past the end of your allocation. These out-of-bounds writes have likely corrupted the runtime environment.

This print is also an issue, as it dereferences the GPU pointer on the CPU:
```
printf("info: gels %d\n", *d_info)
```
After correcting those issues, your example works on my machine.

**Comment by XzzX** [comment]
Thanks for pointing this out. Indeed this is the problem. I ported the code over from Cuda and they use a separate array for this information, so I missed it.

Btw, is there something similar to `compute-sanitizer --tool memcheck` in the ROCm software stack to find these kind of out-of-bounds errors? `rocm-gdb` did not help me.

**Comment by cgmb** [comment]
> is there something similar to `compute-sanitizer --tool memcheck` in the ROCm software stack to find these kind of out-of-bounds errors?

Not to my knowledge. At the moment, your only tools for tracking these sorts of issues down are rocgdb and careful thinking.

It's my understanding that support for [AddressSanitizer](https://clang.llvm.org/docs/AddressSanitizer.html) in device code is planned. That tooling would be able to find out-of-bounds writes on the GPU, though you would have to use a copy of rocSOLVER built with the ASan flags to catch out-of-bounds writes that occur within the library code.

**Comment by XzzX** [comment]
Thank you for your fast response!
