### ISSUE TITLE
Poor performance of jacobi eigensolver routine.

### ISSUE THREAD

**Issue by elbriggs** [ROCmSoftwarePlatform/rocSOLVER#484]
We've found the CUDA jacobi eigensolvers useful for certain matrix size ranges so I tried the rocsolver versions. For rocsolver_dsygvj with N=240 using a Radeon VII I'm seeing performance an order of magnitude or more worse than lapacks dsygvd running on a single CPU core. I enabled profile logging and have included the output from a run that did 4 total calls to rocsolver_dsygvj. I am wondering if this the expected level of performance at this point or is it possible there is something wrong in my machines setup?

------- PROFILE -------
rocsolver_sygvj_hegvj_template: Calls: 4, Total Time: 3262.748 ms (in nested functions: 3262.723 ms)
    sygv_update_info: Calls: 4, Total Time: 4.217 ms
    rocsolver_syevj_heevj_template: Calls: 4, Total Time: 2895.013 ms (in nested functions: 2895.002 ms)
        syevj_small_kernel<T>: Calls: 4, Total Time: 2895.002 ms
    rocsolver_trsm_lower_template: Calls: 4, Total Time: 1.259 ms (in nested functions: 1.248 ms)
        conj_nonunit_backward_substitution_kernel<T>: Calls: 4, Total Time: 1.248 ms
    rocsolver_sygst_hegst_template: Calls: 4, Total Time: 121.691 ms (in nested functions: 121.644 ms)
        rocblas_syr2k_template: Calls: 12, Total Time: 6.292 ms
        rocblas_symm_template: Calls: 24, Total Time: 4.878 ms
        rocsolver_trsm_lower_template: Calls: 24, Total Time: 3.027 ms (in nested functions: 2.986 ms)
            nonunit_forward_substitution_kernel<T>: Calls: 12, Total Time: 1.653 ms
            conj_nonunit_forward_substitution_kernel<T>: Calls: 12, Total Time: 1.333 ms
        rocsolver_sygs2_hegs2_template: Calls: 16, Total Time: 107.447 ms (in nested functions: 96.767 ms)
            rocblas_trsv_template: Calls: 944, Total Time: 52.673 ms
            rocblas_syr2_template: Calls: 944, Total Time: 18.072 ms
            rocblas_scal_template: Calls: 944, Total Time: 11.694 ms
            sygs2_set_diag1: Calls: 960, Total Time: 14.328 ms
    rocsolver_potrf_template: Calls: 4, Total Time: 240.543 ms (in nested functions: 240.493 ms)
        rocblas_syrk_template: Calls: 8, Total Time: 154.154 ms
        rocsolver_trsm_lower_template: Calls: 8, Total Time: 1.809 ms (in nested functions: 1.789 ms)
            conj_nonunit_forward_substitution_kernel<T>: Calls: 8, Total Time: 1.789 ms
        chk_positive<U>: Calls: 12, Total Time: 0.175 ms
        rocsolver_potf2_template: Calls: 12, Total Time: 83.880 ms (in nested functions: 82.554 ms)
            rocblas_gemv_template: Calls: 948, Total Time: 32.727 ms
            sqrtDiagOnward<T>: Calls: 960, Total Time: 13.006 ms
            rocblas_dot_template: Calls: 960, Total Time: 21.591 ms
            rocblas_scal_template: Calls: 948, Total Time: 15.074 ms
            reset_info: Calls: 12, Total Time: 0.156 ms
        reset_info: Calls: 12, Total Time: 0.475 ms
iota_n<T>: Calls: 4, Total Time: 0.823 ms

**Comment by cgmb** [comment]
The initial implementation was very naive. The first round of optimizations are being done in #460.

**Comment by cgmb** [comment]
At least, I _think_ that should improve this case. @tfalders would know best.

**Comment by elbriggs** [comment]
Thanks. Looks like good progress.

**Comment by dcyca** [comment]
@elbriggs - Can you share details of what matrix size ranges are of interest?  That could be helpful in focusing our optimization efforts.

**Comment by elbriggs** [comment]
@dcyca it's being used in an electronic structure code where the scaling properties are such that with the cusolver jacobi routines we see the most benefit in the range 1000 < N < 10000.

**Comment by elbriggs** [comment]
@dcyca I should add that is on Summit at ORNL to give you some idea of the hardware involved. Those ranges may change with Frontier but I don't have a good estimate on that just yet.

**Comment by tfalders** [comment]
On my Vega 10 machine, the optimized implementation is showing a 95% improvement over the original implementation for N =240, and a 99% improvement for N = 1000. I'm sure there's still room for improvement, but this should go a long way to making the method usable.

**Comment by elbriggs** [comment]
Excellent. I would add that for our purposes the jacobi solvers are quite useful even if they aren't as fast as the standard solvers at max precision. The reason is that our solution process is iterative and full precision isn't required until near the end so adjusting the value of abstol can provide nice gains.

**Comment by elbriggs** [comment]
After wrestling with it for a while I got this (and an updated rocblas) built and installed on my workstation. The machine is a 32 core Epyc with dual Radeon VIIs. I ran one of my test cases using the old rocsolver_dsygvj, the new one and scalapack for a CPU based comparison. Results listed below are the total times spent in the eigensolver over the course of the run (N=240) which involved multiple calls to the eigensolver.

Old              10.43 seconds
New               0.16 seconds
Scalapack     0.80 seconds

So yep I'd say it's usable now :)
Our real target is much larger jobs on crusher/frontier where eigensolver performance is crticial but I don't know yet if it's possible to build and use the new version there.

**Comment by tfalders** [comment]
The PR has been merged now and should make it into the next rocSOLVER release. I think we should be good to close this issue now, yes?

**Comment by elbriggs** [comment]
Yes. Thanks! It's working quite well for our application which applies it to a sequence of matrices that get progressively more diagonal as the calculation proceeds. You can see that clearly in the results below (N=1152). 

rocsolver_dsygvj time =       0.669077
rocsolver_dsygvj time =       0.235770
rocsolver_dsygvj time =       0.162654
rocsolver_dsygvj time =       0.162455
rocsolver_dsygvj time =       0.089232
rocsolver_dsygvj time =       0.089138

**Comment by tfalders** [comment]
Glad to hear it! If you run into any other issues, please reach out to us.
