### ISSUE TITLE
add topic tags in About section

### ISSUE THREAD

**Issue by Beliavsky** [ROCmSoftwarePlatform/rocSOLVER#679]
I suggest adding topics such as `lapack`, `linear-algebra`, `rocm` in the About section at https://github.com/ROCm/rocSOLVER , as described at https://docs.github.com/en/enterprise-server@3.10/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by tfalders** [comment]
Thanks, @Beliavsky! I will look into adding some labels right away.

@ROCm/rocm-documentation Do we have any standard labels that should be added in addition to those mentioned above?

**Comment by tfalders** [comment]
I've added the labels and will now close this issue
